# USER TESTS

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

# SESSION TESTS

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

# CHARACTER TESTS

### Character pdf download
GET http://localhost:3000/characters
Content-Type: application/json

